### ISSUE TITLE
A download issue has arisen.

### ISSUE THREAD

**Issue by bluebear78** [sokcuri/multi-speaker-tacotron-tensorflow#1]
Errors continue to occur on this line.
[python3 download.py park]

liek this

``[!] The pre-trained models are being made available for research purpose only
 [!] 학습된 모델을 연구 이외의 목적으로 사용하는 것을 금지합니다.

 [?] Are you agree on this? 이에 동의하십니까? [y/n] y
park-20171015.tar.gz: 4.00B [00:00, 12.9B/s]
Traceback (most recent call last):
  File "/home/bluebear/tensorflow/lib/python3.5/tarfile.py", line 1629, in gzopen
    t = cls.taropen(name, mode, fileobj, **kwargs)
  File "/home/bluebear/tensorflow/lib/python3.5/tarfile.py", line 1605, in taropen
    return cls(name, mode, fileobj, **kwargs)
  File "/home/bluebear/tensorflow/lib/python3.5/tarfile.py", line 1470, in __init__
    self.firstmember = self.next()
  File "/home/bluebear/tensorflow/lib/python3.5/tarfile.py", line 2279, in next
    tarinfo = self.tarinfo.fromtarfile(self)
  File "/home/bluebear/tensorflow/lib/python3.5/tarfile.py", line 1082, in fromtarfile
    buf = tarfile.fileobj.read(BLOCKSIZE)
  File "/usr/lib/python3.5/gzip.py", line 274, in read
    return self._buffer.read(size)
  File "/usr/lib/python3.5/_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "/usr/lib/python3.5/gzip.py", line 461, in read
    if not self._read_gzip_header():
  File "/usr/lib/python3.5/gzip.py", line 409, in _read_gzip_header
    raise OSError('Not a gzipped file (%r)' % magic)
OSError: Not a gzipped file (b'\n<')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "download.py", line 120, in <module>
    download_checkpoint('park')
  File "download.py", line 103, in download_checkpoint
    tar = tarfile.open(save_path, "r:gz")
  File "/home/bluebear/tensorflow/lib/python3.5/tarfile.py", line 1575, in open
    return func(name, filemode, fileobj, **kwargs)
  File "/home/bluebear/tensorflow/lib/python3.5/tarfile.py", line 1633, in gzopen
    raise ReadError("not a gzip file")
tarfile.ReadError: not a gzip file
``

**Comment by sokcuri** [comment]
Using instead https://github.com/carpedm20/multi-speaker-tacotron-tensorflow (official) repository. Thanks.
